### ISSUE TITLE
Child components overwrite :shared value when :shared specified in opts to om.core/build

### ISSUE THREAD

**Issue by symfrog** [swannodette/om#283] opened 2014-11-27 21:00 UTC
When a child component specifies :shared in opts to om.core/build, then values added by parent components to :shared are not visible to components further down the hierarchy. 

I would suggest that om.core/build merges the parent :shared map with the :shared map specified in the opts argument. 

The current implementation means that if there is any child component in the hierarchy that species :shared, then a parent component would not be able to provide a :shared value to components beyond the point at which the first child specifies :shared. 

The relevant point at which the change would be required is: 

https://github.com/swannodette/om/blob/master/src/om/core.cljs#L889

**Comment by swannodette** [comment] 2015-01-09 15:36
This is not a bug. `:shared` can only be supplied once from the root. The documentation should be fixed to clarify this. If you need to pass some other kind of once only information use `:opts`.

**Closed by swannodette** 2015-01-09 15:36 UTC
